# Generated by Django 4.1.3 on 2022-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
